Lazy commitment zktrie
scroll-tech/stateless-block-verifier pull request #39
Opened 2024-08-29 11:55 UTC by i-m-aditya

2024-08-29 12:04 UTC, lightsing requested changes
Also, please make sure all ci pass before merge/request review

2024-08-29 12:04 UTC, lightsing commented on src/executor/mod.rs
> +            if self.zktrie.is_trie_dirty() {
wrong position, this is wrapped by `debug-account` gate?

2024-09-02 08:30 UTC, lispc commented on Cargo.toml
> +
merged.  the patch line can be removed?

2024-09-02 08:49 UTC, lispc approved these changes

2024-09-02 10:26 UTC, lispc approved these changes

2024-09-02 10:26 UTC, merged